/// Adds an utf-8 header...? only ever used on circuitry so when wiremod arrives...
#define UTF8HEADER "<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' /><meta http-equiv='X-UA-Compatible' content='IE=edge' />"
