//Thirst
/// Maximum amount of hydration the player can have
#define THIRST_LEVEL_THRESHOLD		800
#define THIRST_LEVEL_FULL			600
#define THIRST_LEVEL_VERY_QUENCHED	550
#define THIRST_LEVEL_QUENCHED		450
#define THIRST_LEVEL_BIT_THIRSTY	350
#define THIRST_LEVEL_THIRSTY		250
#define THIRST_LEVEL_PARCHED		150

#define THIRST_LEVEL_START_MIN	250
#define THIRST_LEVEL_START_MAX	400

// Pixel shifting
#define PIXEL_SHIFT_MAXIMUM 16
#define PIXEL_SHIFT_PASSABLE_THRESHOLD 8
