/datum/reagent/consumable/semen
	hydration = 4 * REAGENTS_METABOLISM //thats one way to stay hydrated...

/datum/reagent/consumable/femcum
	hydration = 2 * REAGENTS_METABOLISM //thats one way to stay hydrated...
